---
- name: restart gitlab
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - gitlab
  notify:
    - restart nginx
 
- name: restart nginx
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nginx
