---
- name: restart mailpile
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - mailpile
  notify:
    - restart nginx
 
- name: restart nginx
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nginx
